version: '3.7'
services:
  python:
    build: 
      context: ../
      dockerfile: ./docker/python/Dockerfile
    ports: 
      - "5000:5000"
    environment: 
      - "FLASK_APP=flaskr"
      - "FLASK_ENV=development"
      - "FLASK_SECRET_KEY=dev"
      - "SQLALCHEMY_DATABASE_URI=postgresql://postgres:pass1234@db/recipebook"
      - DROPBOX_API_KEY
    volumes:
      - ../:/usr/src/app
    links:
      - db
    working_dir: "/usr/src/app"
    command: flask run --host 0.0.0.0 --port 5000

  db:
    image: 'postgres:11-alpine'
    ports:
      - "5432:5432"
    container_name: localdb
    restart: always
    volumes:
      - pgsql-data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=pass1234"
      - "POSTGRES_DB=recipebook"

volumes:
  pgsql-data:
